version: "3"

services:
    backend:
        build: .
        restart: unless-stopped
        env_file:
            - ".env"
        ports:
            - "3000:3000"
        volumes:
            - .:/app
            - /app/node_modules
        command: npm run start
